# Generated by Django 4.2.8 on 2023-12-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BooleanField(default=True)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
